sonar.projectKey=masterteo109_SIT753-7.3HD-Jenkins-Pipeline
sonar.projectName=SIT753 Student Platform
sonar.organization=masterteo109
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,logs/**,data/**,*.json
sonar.coverage.exclusions=src/controllers/view.controller.js,src/routes/view.routes.js,src/server.js
sonar.test.exclusions=node_modules/**,coverage/**

sonar.qualitygate.wait=true