sonar.projectKey=sit753-student-platform
sonar.projectName=SIT753 Student Platform
sonar.organization=masterteo109
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,logs/**,data/**,*.json
sonar.test.exclusions=node_modules/**,coverage/**

sonar.qualitygate.wait=true